spring:
  application:
    name: link-service
  config:
    import: "optional:configserver:http://${CONFIG_SERVER_HOST:config-server}:${CONFIG_SERVER_PORT:8888}"
  cloud:
    config:
      fail-fast: true
  jpa:
    properties:
      hibernate.type.json_format_mapper: com.smarturl.hub.link.config.Jackson3JsonFormatMapper
